[package]
name = "bubblesortvis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[dependencies.sfml]
version = "0.23.0-alpha.7"
default-features = false
features = ["graphics"]
